name: Create Repository Dispatch
on:
  push:
    #paths:
   #   - 'managed/src/main/resources/**'
    #  - '.github/workflows/**'
  release:
    types:
      published
jobs:
  createRepositoryDispatch:
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl -XPOST -u "${{ secrets.PAT_USERNAME}}:${{secrets.}}" -H "Accept: application/vnd.github.everest-preview+json"  -H "Content-Type: application/json" https://api.github.com/repos/YOURNAME/APPLICATION_NAME/dispatches --data '{"event_type": "build_application",  "client_payload": {"prerelease": "${{ github.event.release.prerelease }}", "release": "${{github.event.release.tag_name}}"  }}'
