name: Create Repository Dispatch
on:
  #push:
    #paths:
   #   - 'managed/src/main/resources/**'
    #  - '.github/workflows/**'
  release:
    types:
      published
jobs:
  createRepositoryDispatch:
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl -XPOST -u "${{ secrets.PAT_USERNAME}}:${{secrets.REPO_ACCESS_TOKEN}}" -H "Accept: application/vnd.github.everest-preview+json"  -H "Content-Type: application/json" https://api.github.com/repos/Surbhidongaonkar/Use-RD/dispatches --data '{"event_type": "update-on-release",  "client_payload": {"prerelease": "${{ github.event.release.prerelease }}", "release": "${{github.event.release.tag_name}}"  }}'
      - run: |
          curl -XPOST -u "${{ secrets.PAT_USERNAME}}:${{secrets.REPO_ACCESS_TOKEN}}" -H "Accept: application/vnd.github.everest-preview+json"  -H "Content-Type: application/json" https://api.github.com/repos/Surbhidongaonkar/demo-webhook/dispatches --data '{"event_type": "update-on-release",  "client_payload": {"prerelease": "${{ github.event.release.prerelease }}", "release": "${{github.event.release.tag_name}}"  }}'
